name: "Fixpoint - Auto-Fix Security Vulnerabilities"
description: "Automatically detect and fix SQL injection, hardcoded secrets, and XSS vulnerabilities in your pull requests. Deterministic fixes with no AI hallucinations."
author: "IWEB"

inputs:
  github_token:
    description: "GitHub token for API access. Uses the automatic GITHUB_TOKEN by default."
    required: false
    default: ${{ github.token }}
  mode:
    description: "Operation mode: 'warn' posts comments with suggested fixes, 'enforce' automatically applies fixes and commits."
    required: false
    default: "warn"
  base_branch:
    description: "Base branch to compare against for detecting changed files."
    required: false
    default: "main"

outputs:
  violations_found:
    description: "Number of security violations found"
  violations_fixed:
    description: "Number of violations fixed (enforce mode only)"
  status:
    description: "Result status: success, warn_mode, no_findings, error"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: ${{ github.action_path }}/requirements.txt
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    
    - name: Install Semgrep
      run: pip install semgrep
      shell: bash
    
    - name: Run Fixpoint
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_BASE_BRANCH: ${{ inputs.base_branch }}
        FIXPOINT_ACTION_PATH: ${{ github.action_path }}
      run: python ${{ github.action_path }}/entrypoint.py
      shell: bash

branding:
  icon: "shield"
  color: "purple"
