name: "Fixpoint - Auto-Fix Security Vulnerabilities"
description: "Auto-fix SQLi, secrets, XSS, command injection, path traversal in Python + JS/TS. Deterministic, no AI."
author: "IWEB"

inputs:
  github_token:
    description: "GitHub token for API access. Uses the automatic GITHUB_TOKEN by default."
    required: false
    default: ${{ github.token }}
  mode:
    description: "Operation mode: 'warn' posts comments with suggested fixes, 'enforce' automatically applies fixes and commits."
    required: false
    default: "warn"
  base_branch:
    description: "Base branch to compare against for detecting changed files."
    required: false
    default: "main"
  max_diff_lines:
    description: "Max lines changed per auto-fix commit (safety rail). Exceeds = no commit."
    required: false
    default: "500"
  test_before_commit:
    description: "Run tests before committing. If tests fail, no commit."
    required: false
    default: "false"
  test_command:
    description: "Command to run when test_before_commit is true (e.g. pytest, npm test)."
    required: false
    default: "pytest"

outputs:
  violations_found:
    description: "Number of security violations found"
  violations_fixed:
    description: "Number of violations fixed (enforce mode only)"
  status:
    description: "Result status: success, warn_mode, no_findings, error"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: "pip"
        cache-dependency-path: ${{ github.action_path }}/requirements.txt
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    
    - name: Install Semgrep
      run: pip install semgrep
      shell: bash
    
    - name: Run Fixpoint
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_BASE_BRANCH: ${{ inputs.base_branch }}
        FIXPOINT_ACTION_PATH: ${{ github.action_path }}
        FIXPOINT_MAX_DIFF_LINES: ${{ inputs.max_diff_lines }}
        FIXPOINT_TEST_BEFORE_COMMIT: ${{ inputs.test_before_commit }}
        FIXPOINT_TEST_COMMAND: ${{ inputs.test_command }}
      run: python ${{ github.action_path }}/entrypoint.py
      shell: bash

    - name: Upload Fixpoint artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: fixpoint-artifacts
        if-no-files-found: ignore
        path: |
          patch-plan.json
          findings.json
          fixpoint-results.sarif.json

branding:
  icon: "shield"
  color: "purple"
