name: "AuditShield"
description: "Auto-fix security vulnerabilities in PRs. Detects SQL injection, hardcoded secrets, and XSS. Applies deterministic fixes and sets status checks."
author: "zariffromlatif"

inputs:
  github_token:
    description: "GitHub token for API access (use secrets.GITHUB_TOKEN)"
    required: false
  base_branch:
    description: "Base branch to compare against"
    required: false
    default: "main"
  mode:
    description: "Mode: 'warn' (comments only) or 'enforce' (auto-fix commits)"
    required: false
    default: "warn"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    
    - name: Install Semgrep
      run: pip install semgrep
      shell: bash
    
    - name: Run AuditShield
      env:
        GITHUB_TOKEN: ${{ inputs.github_token || github.token }}
        INPUT_MODE: ${{ inputs.mode }}
        INPUT_BASE_BRANCH: ${{ inputs.base_branch }}
        AUDITSHIELD_ACTION_PATH: ${{ github.action_path }}
      run: python ${{ github.action_path }}/entrypoint.py
      shell: bash

branding:
  icon: "shield"
  color: "blue"
