[mypy]
python_version = 3.12
warn_unused_configs = False

[mypy-requests.*]
ignore_missing_imports = True
[mypy-redis.*]
ignore_missing_imports = True
[mypy-yaml.*]
ignore_missing_imports = True
[mypy-github.*]
ignore_missing_imports = True
[mypy-tree_sitter_languages.*]
ignore_missing_imports = True
[mypy-hypothesis.*]
ignore_missing_imports = True

[mypy-webhook.server]
ignore_errors = True
